"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
 
import os

from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@pu6uv_^bd)(nk&n&2y#4n9loqdm-*u5w1w!n1s06l59o!k*cp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'myapp.middleware.AdminSessionMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'KisanConnect',
        'USER': 'root', 
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}  


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
 
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# import os
# from pathlib import Path

# 1. ALWAYS DEFINE THIS FIRST

# BASE DIR

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
SECRET_KEY = 'your-secret-key'
DEBUG = True   # (deploy वेळी False कर)
ALLOWED_HOSTS = []
# ================= STATIC FILES =================

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'myapp/static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ================= MEDIA FILES =================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# # ============================================================
# # EMAIL — Gmail SMTP with App Password
# # ============================================================
# EMAIL_BACKEND     = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST        = 'smtp.gmail.com'
# EMAIL_PORT        = 587
# EMAIL_USE_TLS     = True   # Port 587 uses TLS — correct
# EMAIL_USE_SSL     = False  # NEVER True when EMAIL_USE_TLS is True
# EMAIL_HOST_USER   = 'shivanipimpe99@gmail.com'
# EMAIL_HOST_PASSWORD = 'ckbp xbsm ykem gfug'  # Gmail App Password (16 chars)
# DEFAULT_FROM_EMAIL  = 'shivanipimpe99@gmail.com'
# EMAIL_TIMEOUT     = 30
# # ============================================================


#============================================================
# EMAIL — Updated Config
# ============================================================
# EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST          = 'smtp.gmail.com'
# EMAIL_PORT          = 587
 
# EMAIL_HOST_USER     = 'shivanipimpe99@gmail.com'
# # PASTE YOUR NEW 16-DIGIT CODE HERE (NO SPACES)
# EMAIL_HOST_PASSWORD = 'ckbp xbsm ykem gfug' 
# DEFAULT_FROM_EMAIL  = 'shivanipimpe99@gmail.com'


# # Add this at the bottom of settings.py 
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# settings.py

# You can add the specific ngrok URL or use '*' for testing only
# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.app'] 