# Generated by Django 4.2 on 2026-03-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Organic', 'Organic Products'), ('Seeds', 'Seeds'), ('Fertilizers', 'Fertilizers'), ('Pesticides', 'Pesticides'), ('Tools', 'Farm Tools')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
