# Generated by Django 4.2 on 2026-03-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='available_weights',
            field=models.CharField(default='1kg, 5kg, 10kg', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='best_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Organic', 'Organic'), ('Seeds', 'Seeds'), ('Fertilizers', 'Fertilizers'), ('Pesticides', 'Pesticides'), ('Tools', 'Tools')], max_length=50),
        ),
    ]
