# Generated by Django 4.2 on 2026-04-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_contactmessage_alter_review_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='replies/docs/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
