# Generated by Django 4.2 on 2026-04-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_admindocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminreply',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='adminreply',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adminreply',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='admin_replies/'),
        ),
        migrations.AlterField(
            model_name='adminreply',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
